### PR TITLE
Fix/NAS-106/Update CKEditor to version 4.14.1

### PR DESCRIPTION
**Pull request by andrey-ponamarev**
**Related to task:**  https://oat-sa.atlassian.net/browse/NSA-106
**Description:** The main reason of updating is to fix issue by copy/paste content from Word Document. The issue and other bugs are fixed in that release and listed in CHANGES file.
Assets are copied from upgraded [library](https://github.com/oat-sa/ckeditor-dev/pull/16)

**Requires:**
- [ ]  Should be released together with [@oat-sa/tao-item-runner-qti](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/86)

**How to test:**
Is described on [PR](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/86)

### CODE REVIEW

**Comment by bziondik** [comment]
Is information from `lib/ckeditor/README.md` moved somewhere?

**Comment by bziondik** [comment]
Can we reduce the size, for example, remove the folder `samples`?

**Comment by andrey-ponamarev** [comment]
Excluded files for release are adjusted in the [config](https://github.com/oat-sa/ckeditor-dev/blob/develop/dev/builder/build-config.js#L29)
> Is information from `lib/ckeditor/README.md` moved somewhere?

`README.md` is excluded from building assets, if you want I can add but I think the project should have that file instead.

> Can we reduce the size, for example, remove the folder samples?

Yes. We can remove it for build

**Comment by bziondik** [comment]
@andrey-ponamarev
I think we should have some information here how to update CKEditor, or reference to https://github.com/oat-sa/ckeditor-dev
Samples folder should be removed, and here placed a reference to samples from https://github.com/oat-sa/ckeditor-dev

**Pull request merged**
